config/routes.rb
Rails.application.routes.draw do
  get 'users/dashboard'
  #get 'dashboard' => 'users#dashboard', as: "user_dashboard"

  root "home#index"

  devise_for :users
  resources :games
  resources :developers
  resources :platforms

  match 'users/:id' => 'users#show', via: :get
  # or 
  get 'users/:id' => 'users#show'
  # or
  resources :users
  resources :posts

  resources :comments, only: [:create]
  resources :tags

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_many :user_developers
  has_many :users, through: :user_developers

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :user_games
  has_many :users, through: :user_games

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  has_many :user_platforms
  has_many :users, through: :user_platforms

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_many :post_tags
  has_many :tags, through: :post_tags

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def self.all_except(post)
    where.not(id: post)
  end


  def self.search(term)
    if term
      self.where("tag.name LIKE ?", "%#{term}%")
    else
      self.all
    end
  end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_games
  has_many :games, through: :user_games

  has_many :user_platforms
  has_many :platforms, through: :user_platforms

  has_many :user_developers
  has_many :developers, through: :user_developers

  has_many :comments
  has_many :posts

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
end

app/models/user_developer.rb
class UserDeveloper < ActiveRecord::Base
  belongs_to :developer
  belongs_to :user
end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/user_platform.rb
class UserPlatform < ActiveRecord::Base
  belongs_to :platform
  belongs_to :user
end

app/models/user_post.rb
class UserPost < ActiveRecord::Base
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @developers = Developer.all
  end

  def create
    @developer = Developer.new(developer_params)

    if @developer.save
      flash[:notice] = "Developer was successfully created"
      redirect_to developer_path(@developer)
    else
      flash.now[:error] = "An error occurred while saving this developer"
      #render :new
    end
  end

def show
  @developer = Developer.find(params[:id])
  @posts = Post.all
end

def new
@developer = Developer.new
end


def edit
  @developer = Developer.find(params[:id])
end

def update
  @developer = Developer.find(params[:id])
     if @developer.update(developer_params)
       redirect_to developer_path(@developer), notice: "Developer was successfully updated!"
     else
       flash.now[:error] = "An error occurred when updating this developer"
       render :edit
     end
end

def destroy
  @developer = Developer.find(params[:id])
  @developer.destroy
  redirect_to developer_path, notice: "Developer was successfully deleted"
end


  private

def developer_params
  params.require(:developer).permit(:name, :photo)
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      flash[:notice] = "Tag was successfully created"
      redirect_to tags_path
    else
      flash.now[:error] = "An error occurred while saving this tag"
      #render :new
    end
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tag_path(@tag), notice: "Tag was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this tag"
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path, notice: "Tag was successfully deleted"
  end


  private

#   def find_character
#     @character = Character.find(params[:id])
#   end

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/developers/_form.html.erb
<%= form_for @developer, html: { multipart: true } do |f| %>

<% if @developer.errors.any? %>
<% @developer.errors.full_messages.each do |message| %>
<p><%= message %></p>
<% end %>
<% end %>

<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>

<%= f.label :photo %><br>
<p>
  <%= image_tag @developer.photo.url(:large), class: "" %>
</p>
  <p>
    <%= f.file_field :photo  %>
  </p>  

<%= f.submit %>
<% end %>

app/views/developers/edit.html.erb
<h1>Edit Developer</h1>

<%= link_to "Back to Developer List", developers_path %>

<%= render 'form' %>

app/views/developers/index.html.erb
<div class='row'>
<% if current_user %>
<%= link_to "Create New Developer", new_developer_path %>
<% end %>
<div id="" class="">
    <% @developers.each do |developer| %>
    <%= link_to developer_path(developer) do %>
    <div class="col-md-4 developer">
      <h2><%= developer.name %></h2>      
      <p><%= image_tag developer.photo.url(:medium), class: "" %></p>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/developers/new.html.erb
<h1>Add New Developer</h1>

<%= link_to "Back to Developer List", developers_path %>

<%= render 'form' %>

app/views/developers/show.html.erb
<div class="row">
  <div class="col-md-12">
<p>
  <strong>Developer Name:</strong> <%= @developer.name %>
</p>
<p>
  <%= image_tag @developer.photo.url(:large), class: "" %>  
</p>
<% if current_user %>
<%= link_to "EDIT", edit_developer_path(@developer) %>
<%= link_to "DELETE", developer_path(@developer), method: :delete, data: {confirm: "Are you sure you want to delete this developer?"}%>
<% end %>
</div>
</div>
<hr />


<div class="row">    
    <h3>Posts</h3>

    <% @posts.each do |post| %>
    <div class="col-md-4 post">
      <%= link_to post_path(post) do %>
      <div>
      <h4><%= post.title %></h4>
      <p><%= image_tag post.photo.url(:medium), class: "" %></p>
      <p><%= post.body %></p>
      <p>on <%= post.created_at.to_formatted_s(:long) %></p>
      </div>
      <% end %>
      <h6>Comments</h6>
      <% @comments = post.comments %>
      <% @comments.each do |comment| %>
      <p><%= comment.body %>
      by: <%= "#{comment.user.email}"+' on '+"#{comment.created_at.to_formatted_s(:long)}" %></p>
        <% end %>
      </div>
      <% end %>
  </div>
</div>