config/routes.rb
Rails.application.routes.draw do
  get 'users/dashboard'
  #get 'dashboard' => 'users#dashboard', as: "user_dashboard"

  root "home#index"

  devise_for :users
  resources :games
  resources :developers
  resources :platforms

  match 'users/:id' => 'users#show', via: :get
  # or 
  get 'users/:id' => 'users#show'
  # or
  resources :users
  resources :posts

  resources :comments, only: [:create]
  resources :tags

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_many :user_developers
  has_many :users, through: :user_developers

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :user_games
  has_many :users, through: :user_games

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  has_many :user_platforms
  has_many :users, through: :user_platforms

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_many :post_tags
  has_many :tags, through: :post_tags

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def self.all_except(post)
    where.not(id: post)
  end


  def self.search(term)
    if term
      self.where("tag.name LIKE ?", "%#{term}%")
    else
      self.all
    end
  end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_games
  has_many :games, through: :user_games

  has_many :user_platforms
  has_many :platforms, through: :user_platforms

  has_many :user_developers
  has_many :developers, through: :user_developers

  has_many :comments
  has_many :posts

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
end

app/models/user_developer.rb
class UserDeveloper < ActiveRecord::Base
  belongs_to :developer
  belongs_to :user
end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/user_platform.rb
class UserPlatform < ActiveRecord::Base
  belongs_to :platform
  belongs_to :user
end

app/models/user_post.rb
class UserPost < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @platforms = Platform.all
  end

  def create
    @platform = Platform.new(platform_params)

    if @platform.save
      flash[:notice] = "Platform was successfully created"
      redirect_to platform_path(@platform)
    else
      flash.now[:error] = "An error occurred while saving this platform"
      #render :new
    end
  end

def show
  @platform = Platform.find(params[:id])
  @posts = Post.all
end

def new
@platform = Platform.new
end


def edit
  @platform = Platform.find(params[:id])
end

def update
  @platform = Platform.find(params[:id])
     if @platform.update(platform_params)
       redirect_to platform_path(@platform), notice: "Platform was successfully updated!"
     else
       flash.now[:error] = "An error occurred when updating this platform"
       render :edit
     end
end

def destroy
  @platform = Platform.find(params[:id])
  @platform.destroy
  redirect_to platform_path, notice: "Platform was successfully deleted"
end


  private

#   def find_character
#     @character = Character.find(params[:id])
#   end

def platform_params
  params.require(:platform).permit(:name, :photo)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/platforms/_form.html.erb
<%= form_for @platform, html: { multipart: true } do |f| %>

<% if @platform.errors.any? %>
<% @platform.errors.full_messages.each do |message| %>
<p><%= message %></p>
<% end %>
<% end %>

<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>

<%= f.label :photo %><br>
<p>
  <%= image_tag @platform.photo.url(:large), class: "" %>
</p>
  <p>
    <%= f.file_field :photo  %>
  </p>  

<%= f.submit %>
<% end %>

app/views/platforms/edit.html.erb
<h1>Edit PLatform</h1>

<%= link_to "Back to Platform List", platforms_path %>

<%= render 'form' %>

app/views/platforms/index.html.erb
<div class='row'>
<% if current_user %>
<%= link_to "Create New Platform", new_platform_path %>
<% end %>
<div id="" class="">
    <% @platforms.each do |platform| %>
    <%= link_to platform_path(platform) do %>
    <div class="col-md-4 platform">
      <h2><%= platform.name %></h2>      
      <p><%= image_tag platform.photo.url(:medium), class: "" %></p>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/platforms/new.html.erb
<h1>Add New Platform</h1>

<%= link_to "Back to Platform List", platforms_path %>

<%= render 'form' %>

app/views/platforms/show.html.erb
<div class="row">
  <div class="col-md-12">
<p>
  <strong>Platform Name:</strong> <%= @platform.name %>
</p>
<p>
  <%= image_tag @platform.photo.url(:large), class: "" %>  
</p>
<% if current_user %>
<%= link_to "EDIT", edit_platform_path(@platform) %>
<%= link_to "DELETE", platform_path(@platform), method: :delete, data: {confirm: "Are you sure you want to delete this platform?"}%>
<% end %>
</div>
</div>
<hr />


<div class="row">    
    <h3>Posts</h3>

    <% @posts.each do |post| %>
    <div class="col-md-4 post">
      <%= link_to post_path(post) do %>
      <div>
      <h4><%= post.title %></h4>
      <p><%= image_tag post.photo.url(:medium), class: "" %></p>
      <p><%= post.body %></p>
      <p>on <%= post.created_at.to_formatted_s(:long) %></p>
      </div>
      <% end %>
      <h6>Comments</h6>
      <% @comments = post.comments %>
      <% @comments.each do |comment| %>
      <p><%= comment.body %>
      by: <%= "#{comment.user.email}"+' on '+"#{comment.created_at.to_formatted_s(:long)}" %></p>
        <% end %>
      </div>
      <% end %>
  </div>
</div>