config/routes.rb
Rails.application.routes.draw do
  get 'users/dashboard'
  #get 'dashboard' => 'users#dashboard', as: "user_dashboard"

  root "home#index"

  devise_for :users
  resources :games
  resources :developers
  resources :platforms

  match 'users/:id' => 'users#show', via: :get
  # or 
  get 'users/:id' => 'users#show'
  # or
  resources :users
  resources :posts

  resources :comments, only: [:create]
  resources :tags

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_many :user_developers
  has_many :users, through: :user_developers

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :user_games
  has_many :users, through: :user_games

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  has_many :user_platforms
  has_many :users, through: :user_platforms

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_many :post_tags
  has_many :tags, through: :post_tags

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def self.all_except(post)
    where.not(id: post)
  end


  def self.search(term)
    if term
      self.where("tag.name LIKE ?", "%#{term}%")
    else
      self.all
    end
  end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_games
  has_many :games, through: :user_games

  has_many :user_platforms
  has_many :platforms, through: :user_platforms

  has_many :user_developers
  has_many :developers, through: :user_developers

  has_many :comments
  has_many :posts

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
end

app/models/user_developer.rb
class UserDeveloper < ActiveRecord::Base
  belongs_to :developer
  belongs_to :user
end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/user_platform.rb
class UserPlatform < ActiveRecord::Base
  belongs_to :platform
  belongs_to :user
end

app/models/user_post.rb
class UserPost < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      flash[:notice] = "Tag was successfully created"
      redirect_to tags_path
    else
      flash.now[:error] = "An error occurred while saving this tag"
      #render :new
    end
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tag_path(@tag), notice: "Tag was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this tag"
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path, notice: "Tag was successfully deleted"
  end


  private

#   def find_character
#     @character = Character.find(params[:id])
#   end

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "User was successfully updated!"
    else
      flash.now[:error] = "An error occurred when updating this User"
    end
  end


  def edit
    @user = User.find(params[:id])
  end

  def dashboard
    @user = User.find(current_user.id)
    @post = Post.new
    @posts = @user.posts.order(created_at: :desc)
  end

  private

  def user_params
    params.require(:user).permit(:title, :genre, :description,:photo, :game_ids => [],:developer_ids => [],:platform_ids=>[])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<div class="row user-panel">
  <div class="col-md-6">
    <h3>User Panel <%= link_to "edit", edit_user_path(@user)%></h3>
    <p><strong>Logged In As:</strong> <%= @user.email %></p>
    <p>
  <%= image_tag @user.photo.url(:medium), class: "" %>  
</p>
</div>

<div class="col-md-6">
<h3>Following</h3>

  <p>Followed Games</p>
    <ul>
      <% @user.games.each do |game| %>
      <li><%= game.title %></li>
      <% end %>
    </ul>


    <p>Followed Platforms</p>
    <ul>
      <% @user.platforms.each do |platform| %>
      <li><%= platform.name %></li>
      <% end %>
    </ul>


    <p>Followed Developers</p>
    <ul>
      <% @user.developers.each do |developer| %>
      <li><%= developer.name %></li>
      <% end %>
    </ul>

  </div>
</div>
<hr />
<div class='row'>
  <div class="col-md-6">
    <% if current_user %>
      <h3>Create New Post</h3>
      <%= form_for @post do |f| %>
        <p>
          <%= f.label :title %><br/>
          <%= f.text_area :title, cols:"50",rows:"1" %>
        </p>
        <p>
          <%= f.label :photo %>
        </p>
        <p>
          <%= f.file_field :photo  %>
        </p>
        <p>
          <%= f.label :teaser %><br/>
          <%= f.text_area :teaser, cols: "50", rows: "5" %>
        </p>
        <p>
          <%= f.label :body %><br/>
          <%= f.text_area :body, cols: "70", rows: "10" %>
        </p>

        <h4>Tags</h4>
        <p>
          <%= collection_check_boxes(:post, :tag_ids, Tag.all, :id, :name)%>
        </p>

          <%= f.hidden_field :user_id, value: current_user.id %>  
          <%= f.submit %>
      <% end %>
      <hr/>
    <% end %>
  </div>
<div class="col-md-6">    
  <h3>My Previous Posts</h3>

    <% @posts.each do |post| %>
    <div class="post">
      <%= link_to post_path(post) do %>
      <div>
      <h4><%= post.title %></h4>
      <p><%= image_tag post.photo.url(:medium), class: "" %></p>
      <p><%= post.body %></p>
      <p>on <%= post.created_at.to_formatted_s(:long) %></p>
      </div>
      <% end %>
      <h6>Comments</h6>
      <% @comments = post.comments %>
      <% @comments.each do |comment| %>
      <p><%= comment.body %>
      by: <%= "#{comment.user.email}"+' on '+"#{comment.created_at.to_formatted_s(:long)}" %></p>
        <% end %>
      </div>
      <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-8">
<h2>Edit User</h2>

<%= form_for @user do |f| %>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>
<br/>



<%= form_for @user do |f| %>
<%= f.label :photo %><br>
<p>
  <%= image_tag @user.photo.url(:large), class: "" %>
</p>
  <p>
    <%= f.file_field :photo  %>
  </p>  
     <%= f.submit %>
 <% end %>

 </div>

<div class="col-md-4">
<h1>Following</h1>
<h3>Followed Games</h3>
 <%= form_for @user do |f| %>
  <p>
  <%= collection_check_boxes(:user, :game_ids, Game.all, :id, :title)%>
  </p>
     <%= f.submit %>
 <% end %>

<h3>Followed Platforms</h3>
 <%= form_for @user do |f| %>
  <p>
  <%= collection_check_boxes(:user, :platform_ids, Platform.all, :id, :name)%>
  </p>
     <%= f.submit %>
 <% end %>

  <h3>Followed Developers</h3>
 <%= form_for @user do |f| %>
  <p>
  <%= collection_check_boxes(:user, :developer_ids, Developer.all, :id, :name)%>
  </p>
   <%= f.submit %>
 <% end %>
<br/>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
<div class="col-md-8">
<h1>User Settings</h1>
<p><%= link_to "edit", edit_user_path(@user)%></p>
<p><strong>User:</strong> <%= @user.email %>
</p>


<p>
  <%= image_tag @user.photo.url(:large), class: "" %>  
</p>
</div>

<div class="col-md-4">
<h1>Following</h1>
<p>Followed Games</p>
<ul>
  <% @user.games.each do |game| %>
    <li><%= game.title %></li>
  <% end %>
</ul>

<p>Followed Platforms</p>
<ul>
  <% @user.platforms.each do |platform| %>
    <li><%= platform.name %></li>
  <% end %>
</ul>


<p>Followed Developers</p>
<ul>
  <% @user.developers.each do |developer| %>
    <li><%= developer.name %></li>
  <% end %>
</ul>

</div>
</div>