config/routes.rb
Rails.application.routes.draw do
  get 'users/dashboard'
  #get 'dashboard' => 'users#dashboard', as: "user_dashboard"

  root "home#index"

  devise_for :users
  resources :games
  resources :developers
  resources :platforms

  match 'users/:id' => 'users#show', via: :get
  # or 
  get 'users/:id' => 'users#show'
  # or
  resources :users
  resources :posts

  resources :comments, only: [:create]
  resources :tags

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_many :user_developers
  has_many :users, through: :user_developers

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :user_games
  has_many :users, through: :user_games

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  has_many :user_platforms
  has_many :users, through: :user_platforms

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_many :post_tags
  has_many :tags, through: :post_tags

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def self.all_except(post)
    where.not(id: post)
  end


  def self.search(term)
    if term
      self.where("tag.name LIKE ?", "%#{term}%")
    else
      self.all
    end
  end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_games
  has_many :games, through: :user_games

  has_many :user_platforms
  has_many :platforms, through: :user_platforms

  has_many :user_developers
  has_many :developers, through: :user_developers

  has_many :comments
  has_many :posts

  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", small: "32x32>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
end

app/models/user_developer.rb
class UserDeveloper < ActiveRecord::Base
  belongs_to :developer
  belongs_to :user
end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/user_platform.rb
class UserPlatform < ActiveRecord::Base
  belongs_to :platform
  belongs_to :user
end

app/models/user_post.rb
class UserPost < ActiveRecord::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GxB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container"> 
    <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">GAMERxBLOGGER</a>
          </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "GAMEs", games_path %></li>
          <li><a href="<%= platforms_path %>">PLATFORMs</a></li>
          <li><a href="<%= developers_path %>">DEVELOPERs</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li><%= link_to "myDASHBOARD", users_dashboard_path %></li>
          <li><%= link_to "Log Off", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Log In", user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div>
      <% flash.each do |name, msg| %>
      <div class="<%= name %>">
      <%= msg %>
      </div>
      <% end %>
    </div>
    <%= yield %>
    <footer id="footer">
      <a class="navbar-brand" href="<%= root_path %>">GAMERxBLOGGER<span> by Alex Zeng</span></a>
    </footer>
  </div>
</body>
</html>